version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y git 
      - run: apt-get install -y curl 
      - run: apt-get install -y libopencv-dev 
      - run: apt-get install -y ffmpeg
      - run: apt-get install -y build-essential
      - run: apt-get install -y libssl-dev
      - run: apt-get install -y clang libclang-dev
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y

workflows:
  build_and_test:
    jobs:
      - build
