version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git curl libopencv-dev ffmpeg build-essential libssl-dev clang libclang-dev
            curl https://sh.rustup.rs -sSf | sh -s -- -y

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

